template: "templates/client_template.py.mako"
clientType: realtimeitl3
templateArgs: # Strings are added to client_template.py.mako
  tasktype: realtimeitl3
  clientTaskName: RealtimeITL3
  parentClassFile: realtimerobotplanningclient
  parentClassName: RealtimeRobotPlanningClient
  extraSuperConstructorArgs: |
    robotname=robotname,
    robotspeed=robotspeed,
    robotaccelmult=robotaccelmult,
    envclearance=envclearance,
    robotBridgeConnectionInfo=robotBridgeConnectionInfo,
  extraConstructorArgs: robotname='', robotspeed=None, robotaccelmult=None, envclearance=10.0, robotBridgeConnectionInfo=None,
  extraClassAttributes:
  extraConstructorArgsDocstringLines: |
    robotname (str, optional): Name of the robot, e.g. VP-5243I
    robotspeed (float, optional): Speed of the robot, e.g. 0.4
    robotaccelmult (float, optional): Optional multiplier for the robot acceleration.
    envclearance (str, optional): Environment clearance in millimeter, e.g. 20
    robotBridgeConnectionInfo (str, optional): dict holding the connection info for the robot bridge.
  extraConstructorContent:
  extraClientContent:
  extraClientStaticFunctions:
include:
  - components_realtimerobot.yaml
x-specModifications:
  services:
    SetJointValues:
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                jointvalues:
                  paramOrderingIndex: 0
                robotname:
                  paramOrderingIndex: 1
                timeout:
                  $merge: "#/components/Internal_ExecuteCommandParameters/timeout"
                  paramOrderingIndex: 2
                kwargs: {}
    GetITLState:
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                robotname:
                  paramOrderingIndex: 0
                timeout:
                  $merge: "#/components/Internal_ExecuteCommandParameters/timeout"
                  paramOrderingIndex: 1
                fireandforget:
                  $merge: "#/components/Internal_ExecuteCommandParameters/fireandforget"
                  paramOrderingIndex: 2
                kwargs: {}
    ExecuteTrajectory:
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                identifier:
                  paramOrderingIndex: 0
                trajectories:
                  paramOrderingIndex: 1
                statevalues:
                  paramOrderingIndex: 2
                stepping:
                  paramOrderingIndex: 3
                istep:
                  paramOrderingIndex: 4
                cycles:
                  paramOrderingIndex: 5
                restorevalues:
                  paramOrderingIndex: 6
                envclearance:
                  paramOrderingIndex: 7
                robotspeed:
                  paramOrderingIndex: 8
                robotaccelmult:
                  paramOrderingIndex: 9
                timeout:
                  $merge: "#/components/Internal_ExecuteCommandParameters/timeout"
                  paramOrderingIndex: 10
                fireandforget:
                  $merge: "#/components/Internal_ExecuteCommandParameters/fireandforget"
                  paramOrderingIndex: 11
    ExecuteTrajectoryStep:
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                reverse:
                  paramOrderingIndex: 0
                envclearance:
                  paramOrderingIndex: 1
                robotspeed:
                  paramOrderingIndex: 2
                robotaccelmult:
                  paramOrderingIndex: 3
                timeout:
                  $merge: "#/components/Internal_ExecuteCommandParameters/timeout"
                  paramOrderingIndex: 4
                fireandforget:
                  $merge: "#/components/Internal_ExecuteCommandParameters/fireandforget"
                  paramOrderingIndex: 5
    PauseExecuteTrajectory:
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                timeout:
                  $merge: "#/components/Internal_ExecuteCommandParameters/timeout"
                  paramOrderingIndex: 0
                fireandforget:
                  $merge: "#/components/Internal_ExecuteCommandParameters/fireandforget"
                  paramOrderingIndex: 1
    ResumeExecuteTrajectory:
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                timeout:
                  $merge: "#/components/Internal_ExecuteCommandParameters/timeout"
                  paramOrderingIndex: 0
                fireandforget:
                  $merge: "#/components/Internal_ExecuteCommandParameters/fireandforget"
                  paramOrderingIndex: 1
    ComputeRobotConfigsForCommandVisualization:
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                executiongraph:
                  paramOrderingIndex: 0
                commandindex:
                  paramOrderingIndex: 1
                timeout:
                  $merge: "#/components/Internal_ExecuteCommandParameters/timeout"
                  paramOrderingIndex: 2
                  default: 2
                fireandforget:
                  $merge: "#/components/Internal_ExecuteCommandParameters/fireandforget"
                  paramOrderingIndex: 3
                kwargs: {}
    ComputeRobotJointValuesForCommandVisualization:
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                program:
                  paramOrderingIndex: 0
                commandindex:
                  paramOrderingIndex: 1
                timeout:
                  $merge: "#/components/Internal_ExecuteCommandParameters/timeout"
                  paramOrderingIndex: 2
                  default: 2
                fireandforget:
                  $merge: "#/components/Internal_ExecuteCommandParameters/fireandforget"
                  paramOrderingIndex: 3
                kwargs: {}
    PlotProgramWaypoints:
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                timeout:
                  $merge: "#/components/Internal_ExecuteCommandParameters/timeout"
                  paramOrderingIndex: 0
                  default: 1
                fireandforget:
                  $merge: "#/components/Internal_ExecuteCommandParameters/fireandforget"
                  paramOrderingIndex: 1
                  default: true
                kwargs: {}
    StartITLProgram:
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                programName:
                  paramOrderingIndex: 0
                robotspeed:
                  paramOrderingIndex: 1
                robotaccelmult:
                  paramOrderingIndex: 2
                timeout:
                  $merge: "#/components/Internal_ExecuteCommandParameters/timeout"
                  paramOrderingIndex: 3
                fireandforget:
                  $merge: "#/components/Internal_ExecuteCommandParameters/fireandforget"
                  paramOrderingIndex: 4
                kwargs: {}
    StopITLProgram:
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                timeout:
                  $merge: "#/components/Internal_ExecuteCommandParameters/timeout"
                  paramOrderingIndex: 0
                fireandforget:
                  $merge: "#/components/Internal_ExecuteCommandParameters/fireandforget"
                  paramOrderingIndex: 1
                kwargs: {}
    GenerateExecutionGraph:
      description: "Generates a list of commands for the ITL program."
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                programName:
                  paramOrderingIndex: 0
                commandTimeout:
                  paramOrderingIndex: 1
                totalTimeout:
                  paramOrderingIndex: 2
                timeout:
                  $merge: "#/components/Internal_ExecuteCommandParameters/timeout"
                  paramOrderingIndex: 3
                fireandforget:
                  $merge: "#/components/Internal_ExecuteCommandParameters/fireandforget"
                  paramOrderingIndex: 4
                kwargs: {}
    PlotContacts:
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                report:
                  paramOrderingIndex: 0
                timeout:
                  $merge: "#/components/Internal_ExecuteCommandParameters/timeout"
                  paramOrderingIndex: 1
                  default: 1
                fireandforget:
                  $merge: "#/components/Internal_ExecuteCommandParameters/fireandforget"
                  paramOrderingIndex: 2
                kwargs: {}
    PopulateTargetInContainer:
      description: "Populates targets in the container using populateFn."
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                locationName:
                  paramOrderingIndex: 0
                populateTargetUri:
                  paramOrderingIndex: 1
                populateFnName:
                  paramOrderingIndex: 2
                containerMetaData:
                  paramOrderingIndex: 3
                timeout:
                  $merge: "#/components/Internal_ExecuteCommandParameters/timeout"
                  paramOrderingIndex: 4
                  default: 20
                kwargs: {}
