template: "templates/client_template.py.mako"
clientType: realtimeitl3
templateArgs: # Strings are added to client_template.py.mako
  tasktype: realtimeitl3
  clientTaskName: RealtimeITL3
  parentClassFile: realtimerobotplanningclient
  parentClassName: RealtimeRobotPlanningClient
  extraSuperConstructorArgs: robotname=robotname, robotspeed=robotspeed, robotaccelmult=robotaccelmult, envclearance=envclearance, robotBridgeConnectionInfo=robotBridgeConnectionInfo,
  extraConstructorArgs: |
    robotname='',
    robotspeed=None,
    robotaccelmult=None,
    envclearance=10.0,
    robotBridgeConnectionInfo=None,
  # extraClassAttributes: ''
  ### robotname, robotspeed etc. are for passing to realtimerobotclient
  extraClassAttributes: |
    _robotname = None  # Optional name of the robot selected
    _robotspeed = None  # Speed of the robot, e.g. 0.4
    _robotaccelmult = None  # Current robot accel mult
    _envclearance = None  # Environment clearance in millimeters, e.g. 20
    _robotBridgeConnectionInfo = None  # dict holding the connection info for the robot bridge.
  extraConstructorArgsDocstringLines: |
    robotname (str, optional): Name of the robot, e.g. VP-5243I
    robotspeed (float, optional): Speed of the robot, e.g. 0.4
    robotaccelmult (float, optional): Optional multiplier for the robot acceleration.
    envclearance (str, optional): Environment clearance in millimeter, e.g. 20
    robotBridgeConnectionInfo (str, optional): dict holding the connection info for the robot bridge.
  extraConstructorContent: ""
  extraClientContent:
  extraClientStaticFunctions:
generatorSettingsComponents:
  timeout:
    x-doNotAddToPayload: true
    type: number
    default: 10
  fireandforget:
    x-doNotAddToPayload: true
    type: boolean
    default: false
include:
  - components_realtimerobot.yaml
x-specModifications:
  services:
    SetJointValues:
      parameters:
        $merge: "#/components/StandardPlanningServerRequestParameters"
        taskparams:
          properties:
            taskparameters:
              properties:
                jointvalues:
                  paramOrderingIndex: 0
                robotname:
                  paramOrderingIndex: 1
                timeout:
                  $merge: "#/generatorSettingsComponents/timeout"
                  paramOrderingIndex: 2
                kwargs: {}
    GetITLState:
      parameters:
        $merge: "#/components/StandardPlanningServerRequestParameters"
        taskparams:
          properties:
            taskparameters:
              properties:
                robotname:
                  paramOrderingIndex: 0
                timeout:
                  $merge: "#/generatorSettingsComponents/timeout"
                  paramOrderingIndex: 1
                fireandforget:
                  $merge: "#/generatorSettingsComponents/fireandforget"
                  paramOrderingIndex: 2
                kwargs: {}
    ExecuteTrajectory:
      parameters:
        $merge: "#/components/StandardPlanningServerRequestParameters"
        taskparams:
          properties:
            taskparameters:
              properties:
                identifier:
                  paramOrderingIndex: 0
                trajectories:
                  paramOrderingIndex: 1
                statevalues:
                  paramOrderingIndex: 2
                stepping:
                  paramOrderingIndex: 3
                istep:
                  paramOrderingIndex: 4
                cycles:
                  paramOrderingIndex: 5
                restorevalues:
                  paramOrderingIndex: 6
                envclearance:
                  paramOrderingIndex: 7
                robotspeed:
                  paramOrderingIndex: 8
                robotaccelmult:
                  paramOrderingIndex: 9
                timeout:
                  $merge: "#/generatorSettingsComponents/timeout"
                  paramOrderingIndex: 10
                fireandforget:
                  $merge: "#/generatorSettingsComponents/fireandforget"
                  paramOrderingIndex: 11
    ExecuteTrajectoryStep:
      parameters:
        $merge: "#/components/StandardPlanningServerRequestParameters"
        taskparams:
          properties:
            taskparameters:
              properties:
                reverse:
                  paramOrderingIndex: 0
                envclearance:
                  paramOrderingIndex: 1
                robotspeed:
                  paramOrderingIndex: 2
                robotaccelmult:
                  paramOrderingIndex: 3
                timeout:
                  $merge: "#/generatorSettingsComponents/timeout"
                  paramOrderingIndex: 4
                fireandforget:
                  $merge: "#/generatorSettingsComponents/fireandforget"
                  paramOrderingIndex: 5
    PauseExecuteTrajectory:
      parameters:
        $merge: "#/components/StandardPlanningServerRequestParameters"
        taskparams:
          properties:
            taskparameters:
              properties:
                timeout:
                  $merge: "#/generatorSettingsComponents/timeout"
                  paramOrderingIndex: 0
                fireandforget:
                  $merge: "#/generatorSettingsComponents/fireandforget"
                  paramOrderingIndex: 1
    ResumeExecuteTrajectory:
      parameters:
        $merge: "#/components/StandardPlanningServerRequestParameters"
        taskparams:
          properties:
            taskparameters:
              properties:
                timeout:
                  $merge: "#/generatorSettingsComponents/timeout"
                  paramOrderingIndex: 0
                fireandforget:
                  $merge: "#/generatorSettingsComponents/fireandforget"
                  paramOrderingIndex: 1
    ComputeRobotConfigsForCommandVisualization:
      parameters:
        $merge: "#/components/StandardPlanningServerRequestParameters"
        taskparams:
          properties:
            taskparameters:
              properties:
                executiongraph:
                  paramOrderingIndex: 0
                commandindex:
                  paramOrderingIndex: 1
                timeout:
                  $merge: "#/generatorSettingsComponents/timeout"
                  paramOrderingIndex: 2
                  default: 2
                fireandforget:
                  $merge: "#/generatorSettingsComponents/fireandforget"
                  paramOrderingIndex: 3
                kwargs: {}
    ComputeRobotJointValuesForCommandVisualization:
      parameters:
        $merge: "#/components/StandardPlanningServerRequestParameters"
        taskparams:
          properties:
            taskparameters:
              properties:
                program:
                  paramOrderingIndex: 0
                commandindex:
                  paramOrderingIndex: 1
                timeout:
                  $merge: "#/generatorSettingsComponents/timeout"
                  paramOrderingIndex: 2
                  default: 2
                fireandforget:
                  $merge: "#/generatorSettingsComponents/fireandforget"
                  paramOrderingIndex: 3
                kwargs: {}
    PlotProgramWaypoints:
      parameters:
        $merge: "#/components/StandardPlanningServerRequestParameters"
        taskparams:
          properties:
            taskparameters:
              properties:
                timeout:
                  $merge: "#/generatorSettingsComponents/timeout"
                  paramOrderingIndex: 0
                  default: 1
                fireandforget:
                  $merge: "#/generatorSettingsComponents/fireandforget"
                  paramOrderingIndex: 1
                  default: true
                kwargs: {}
    StartITLProgram:
      parameters:
        $merge: "#/components/StandardPlanningServerRequestParameters"
        taskparams:
          properties:
            taskparameters:
              properties:
                programName:
                  paramOrderingIndex: 0
                robotspeed:
                  paramOrderingIndex: 1
                robotaccelmult:
                  paramOrderingIndex: 2
                timeout:
                  $merge: "#/generatorSettingsComponents/timeout"
                  paramOrderingIndex: 3
                fireandforget:
                  $merge: "#/generatorSettingsComponents/fireandforget"
                  paramOrderingIndex: 4
                kwargs: {}
    StopITLProgram:
      parameters:
        $merge: "#/components/StandardPlanningServerRequestParameters"
        taskparams:
          properties:
            taskparameters:
              properties:
                timeout:
                  $merge: "#/generatorSettingsComponents/timeout"
                  paramOrderingIndex: 0
                fireandforget:
                  $merge: "#/generatorSettingsComponents/fireandforget"
                  paramOrderingIndex: 1
                kwargs: {}
    GenerateExecutionGraph:
      parameters:
        $merge: "#/components/StandardPlanningServerRequestParameters"
        taskparams:
          properties:
            taskparameters:
              description: "Generates a list of commands for the ITL program."
              properties:
                programName:
                  paramOrderingIndex: 0
                commandTimeout:
                  paramOrderingIndex: 1
                totalTimeout:
                  paramOrderingIndex: 2
                timeout:
                  $merge: "#/generatorSettingsComponents/timeout"
                  paramOrderingIndex: 3
                fireandforget:
                  $merge: "#/generatorSettingsComponents/fireandforget"
                  paramOrderingIndex: 4
                kwargs: {}
    PlotContacts:
      parameters:
        $merge: "#/components/StandardPlanningServerRequestParameters"
        taskparams:
          properties:
            taskparameters:
              properties:
                report:
                  paramOrderingIndex: 0
                timeout:
                  $merge: "#/generatorSettingsComponents/timeout"
                  paramOrderingIndex: 1
                  default: 1
                fireandforget:
                  $merge: "#/generatorSettingsComponents/fireandforget"
                  paramOrderingIndex: 2
                kwargs: {}
    PopulateTargetInContainer:
      parameters:
        $merge: "#/components/StandardPlanningServerRequestParameters"
        taskparams:
          properties:
            taskparameters:
              description: "Populates targets in the container using populateFn."
              properties:
                locationName:
                  paramOrderingIndex: 0
                populateTargetUri:
                  paramOrderingIndex: 1
                populateFnName:
                  paramOrderingIndex: 2
                containerMetaData:
                  paramOrderingIndex: 3
                timeout:
                  $merge: "#/generatorSettingsComponents/timeout"
                  paramOrderingIndex: 4
                  default: 20
                kwargs: {}
