template: 'templates/client_template.py.mako'
clientType: handeyecalibration
templateArgs:  # Strings that are added to client_template.py.mako
  tasktype: handeyecalibration
  clientTaskName: HandEyeCalibration
  parentClassFile: planningclient
  parentClassName: PlanningClient
  extraSuperConstructorArgs: ''
  extraConstructorArgs: robot,
  extraClassAttributes: "robot = None"
  extraConstructorArgsDocstringLines: |
    robot (str): Name of the robot, e.g. VP-5243I
  extraConstructorContent: |
    self.robot = robot
  extraClientContent: ''
  extraClientStaticFunctions: |
    def _PrepareCommand(self, commandName):
        """Adds common parameters to the command sent to the server 

        Args:
            commandName (str): 
        """
        command = {'command': commandName}
        if self.robot is not None:
          command['robot'] = self.robot
        return command
include:
- components.yaml
x-specModifications:  # These fields add/overwrite spec content. Only the leaf is overwritten. Parent fields are merged if possible.
  services:
    ComputeCalibrationPoses:
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                primarySensorSelectionInfo:
                  paramOrderingIndex: 0
                secondarySensorSelectionInfos:
                  paramOrderingIndex: 1
                numsamples:
                  paramOrderingIndex: 2
                calibboardvisibility:
                  paramOrderingIndex: 3
                  isRequired: true
                toolname:
                  paramOrderingIndex: 4
                calibboardLinkName:
                  paramOrderingIndex: 5
                calibboardGeomName:
                  paramOrderingIndex: 6
                calibboardObjectName:
                  paramOrderingIndex: 7
                minPatternTiltAngle:
                  paramOrderingIndex: 8
                maxPatternTiltAngle:
                  paramOrderingIndex: 9
                dynamicEnvironmentState:
                  paramOrderingIndex: 10
                robot:
                  paramOrderingIndex: 11
                timeout:
                  $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
                  paramOrderingIndex: 12
                  default: 3000.0
                kwargs: {}
    SampleCalibrationConfiguration:
      parameters:
        taskparams:
          properties:
            taskparameters:
              properties:
                primarySensorSelectionInfo:
                  paramOrderingIndex: 0
                secondarySensorSelectionInfos:
                  paramOrderingIndex: 1
                gridindex:
                  paramOrderingIndex: 2
                calibboardvisibility:
                  paramOrderingIndex: 3
                toolname:
                  paramOrderingIndex: 4
                calibboardLinkName:
                  paramOrderingIndex: 5
                calibboardGeomName:
                  paramOrderingIndex: 6
                calibboardObjectName:
                  paramOrderingIndex: 7
                minPatternTiltAngle:
                  paramOrderingIndex: 8
                maxPatternTiltAngle:
                  paramOrderingIndex: 9
                dynamicEnvironmentState:
                  paramOrderingIndex: 10
                robot:
                  paramOrderingIndex: 10
                timeout:
                  $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
                  paramOrderingIndex: 12
                  default: 3000.0
                kwargs: {}